start-at-login = true
after-startup-command = ['exec-and-forget sketchybar']

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[mode.main.binding]
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

ctrl-alt-left = 'move left'
ctrl-alt-down = 'move down'
ctrl-alt-up = 'move up'
ctrl-alt-right = 'move right'

alt-f = 'fullscreen'

alt-shift-space = 'layout floating tiling'
alt-comma = 'layout tiles horizontal vertical'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-b = 'workspace b'
alt-c = 'workspace c'
alt-g = 'workspace g'
alt-m = 'workspace m'
alt-w = 'workspace w'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-b = ['move-node-to-workspace b', 'workspace b']
alt-shift-c = ['move-node-to-workspace c', 'workspace c']
alt-shift-g = ['move-node-to-workspace g', 'workspace g']
alt-shift-m = ['move-node-to-workspace m', 'workspace m']
alt-shift-w = ['move-node-to-workspace w', 'workspace w']

alt-r = 'mode resize'
alt-e = 'balance-sizes'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
check-further-callbacks = true
run = 'layout tiling'

[[on-window-detected]]
if.app-id = 'org.mozilla.com.zen.browser'
if.window-title-regex-substring = 'Picture-in-Picture'
check-further-callbacks = true
run = 'layout floating'

# Application to workspace mapping
# 1 - coding
# 2 - office communication
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'org.gnu.Emacs'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.jetbrains.WebStorm'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.jetbrains.rubymine'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.google.android.studio'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'org.mozilla.com.zen.browser'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = "move-node-to-workspace w"

[[on-window-detected]]
if.app-id = 'com.github.GitHubClient'
run = "move-node-to-workspace g"

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = "move-node-to-workspace m"

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = "move-node-to-workspace m"


[gaps]
inner.horizontal = 2
inner.vertical = 2
