start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"


[mode.main.binding]
alt-q = 'enable off'
alt-tab = 'workspace-back-and-forth'

ctrl-alt-left = 'move left'
ctrl-alt-down = 'move down'
ctrl-alt-up = 'move up'
ctrl-alt-right = 'move right'

alt-f = 'fullscreen'

alt-shift-space = 'layout floating tiling'
alt-comma = 'layout tiles horizontal vertical'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-c = 'workspace c'
alt-g = 'workspace g'
alt-w = 'workspace w'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-c = 'move-node-to-workspace c'
alt-shift-g = 'move-node-to-workspace g'
alt-shift-w = 'move-node-to-workspace w'

alt-r = 'mode resize'
alt-e = 'balance-sizes'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
check-further-callbacks = true
run = 'layout tiling'

# Application to workspace mapping
# 1 - coding
# 2 - office communication
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.jetbrains.WebStorm'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = "move-node-to-workspace w"

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = "move-node-to-workspace c"

[[on-window-detected]]
if.app-id = 'com.github.GitHubClient'
run = "move-node-to-workspace g"


[gaps]
inner.horizontal = 2
inner.vertical = 2
outer.left = 2
outer.bottom = 2
outer.top = 2
outer.right = 2
