# vim:ft=kitty

## name: Ghostty Default Style Dark
## license: MIT
## upstream: https://github.com/nkxxll/ghostty-default-style-dark.nvim
## blurb: kitty port of the ghostty-default-style-dark.nvim palette
##         (lua/ghostty-default-style-dark/colors.lua).

# The basic colors
foreground                      #ffffff
background                      #282c34
selection_foreground            none
selection_background            #363e49

# Cursor colors
cursor                          #ffffff
cursor_text_color               #282c34

# URL underline color when hovering with mouse
url_color                       #7aa6da

# kitty window border colors
active_border_color     #82a2be
inactive_border_color   #666666
bell_border_color       #f0c674

# Tab bar colors
active_tab_foreground   #282c34
active_tab_background   #82a2be
inactive_tab_foreground #c4c8c6
inactive_tab_background #1d1f21
tab_bar_background      #1d1f21

# The basic 16 colors
# black
color0  #1d1f21
color8  #666666

# red
color1  #cc6566
color9  #d54e53

# green
color2  #b6bd68
color10 #b9ca4b

# yellow
color3  #f0c674
color11 #e7c547

# blue
color4  #82a2be
color12 #7aa6da

# magenta
color5  #b294bb
color13 #c397d8

# cyan
color6  #8abeb7
color14 #70c0b1

# white
color7  #c4c8c6
color15 #eaeaea
