# abbreviations
abbr -a -- gst "git status"
abbr -a -- gc "git branch | fzf --height=20% --reverse --info=inline | xargs git checkout"
abbr -a -- gpull "git pull"
abbr -a -- gco "git checkout"
abbr -a -- gpush "git push"
abbr -a -- rserver "rails s "
abbr -a -- rconsole "rails c "
abbr -a -- yd "yarn dev || yarn start "
abbr -a -- bd "bun dev || bun start "
abbr -a -- yt "yarn test"
abbr -a -- yb "yarn build"
abbr -a -- ys "yarn start"
abbr -a -- python "python3"
abbr -a -- pip "pip3"
abbr -a -- nv "nvim"
abbr -a -- vi "nvim"
abbr -a -- v "nvim"
abbr -a -- tr2 "tree -a -L 2"
abbr -a -- cls "clear"
abbr -a -- l "ls -l"
abbr -a -- la "ls -la"
abbr -a -- lf "yazi"
abbr -a -- lfcd "y"
abbr -a -- dc "docker compose"
abbr -a -- du0 "du -h -d 0 */ | sort -h"
abbr -a -- pi "pnpm install"
abbr -a -- pd "pnpm dev"
abbr -a -- pb "pnpm build"
abbr -a -- duh "du -h -d 0 */ | sort -h"
abbr -a -- ytdl "yt-dlp -f bestaudio --no-playlist --extract-audio --audio-format mp3 -o \"~/Downloads/ytdlc/%(title)s.%(ext)s\" "

