#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    active_window_opacity        1.0            \
    auto_balance                 off            \
    bottom_padding               06             \
    focus_follows_mouse          off            \
    insert_feedback_color        0xffd75f5f     \
    layout                       bsp            \
    left_padding                 06             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    mouse_follows_focus          off            \
    mouse_modifier               alt            \
    normal_window_opacity        1.0            \
    right_padding                06             \
    split_ratio                  0.50           \
    split_type                   auto           \
    top_padding                  06             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_gap                   06             \
    window_opacity               off            \
    window_opacity_duration      0.0            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_shadow                off            \
    window_zoom_persist          on             \

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off

echo "yabai configuration loaded.."
